export const styles = {
    container: {
      fontFamily: "'Arial', sans-serif",
      padding: "20px",
      maxWidth: "600px",
      margin: "0 auto",
      border: "1px solid #ccc",
      borderRadius: "10px",
      backgroundColor: "#f9f9f9",
    },
    header: {
      textAlign: "center",
      marginBottom: "20px",
    },
    section: {
      marginBottom: "20px",
      padding: "10px",
      border: "1px solid #ddd",
      borderRadius: "8px",
      backgroundColor: "#fff",
    },
    sectionHeader: {
      marginBottom: "10px",
    },
    inputGroup: {
      display: "flex",
      alignItems: "center",
      marginBottom: "10px",
    },
    label: {
      width: "80px",
    },
    input: {
      flex: "1",
      padding: "8px",
      border: "1px solid #ccc",
      borderRadius: "4px",
    },
    button: {
      padding: "10px 15px",
      border: "none",
      borderRadius: "4px",
      backgroundColor: "#007BFF",
      color: "#fff",
      cursor: "pointer",
      marginTop: "10px",
    },
    deleteButton: {
      padding: "5px 10px",
      border: "none",
      borderRadius: "4px",
      backgroundColor: "#FF0000",
      color: "#fff",
      cursor: "pointer",
      marginLeft: "10px",
    },
    contact: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      padding: "8px",
      border: "1px solid #ddd",
      borderRadius: "4px",
      backgroundColor: "#fdfdfd",
      marginBottom: "8px",
    },
    searchResults: {
      marginTop: "10px",
      border: "1px solid #ddd",
      borderRadius: "4px",
      padding: "8px",
      backgroundColor: "#f9f9f9",
    },
  }